# 2024/DSC/0035/SS
MATHEMATICAL COMPUTING EXAM
SEMESTER 1

# QUESTION 5

In [38]:
import numpy as np #importing the numpy library

## matrix

In [39]:
matrix_x = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(matrix_x) # constructing the matrix

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


## i) transpose

In [40]:
matrix_xT = matrix_x.T
print(matrix_xT) # finding the transpose of the matrix x

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


# ii) determinant

In [42]:
matrix_x_det = np.linalg.det(matrix_x)
print(matrix_x_det) # getting the determinant of the matix x

0.2299999999999999


## iii) decomposing the matrix

In [44]:
from scipy.linalg import lu # importing lower and upper inorder te decompose the matrix

In [34]:
I,L,U = lu(matrix_x)
print(I) # this is the identity matrix
print(L) # this is the lower 
print(U) # this is the upper
# decomposing the matrix using the lower and the upper 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.5        0.72916667 1.        ]]
[[1.         0.2        0.5       ]
 [0.         0.96       0.7       ]
 [0.         0.         0.23958333]]


In [37]:
Q,R = np.linalg.qr(matrix_x)
print(Q)
print(R)

[[-0.88045091  0.38615039 -0.27512557]
 [-0.17609018 -0.80507368 -0.566435  ]
 [-0.44022545 -0.4502713   0.77682515]]
[[-1.13578167 -0.70436073 -1.02132305]
 [ 0.         -1.08806065 -0.90125505]
 [ 0.          0.          0.18611436]]


## iv) transforming the matrix

In [52]:
transformed_matrix_x = np.linalg.norm(matrix_x)
print(transformed_matrix_x)

2.2045407685048604
